import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "./components/AppBar"; // ★ 作成したAppBarをインポート

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppBar /> {/* ★ AppBarをここに追加 */} {children}
      </body>
    </html>
  );
}
